version: 2
updates:
  # Enable version updates for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[gha] "
