---
name: 'lydteamet-helm-publish-action'
description: 'Versions, packages and pushes a helm chart to azurecr'
inputs:
  name:
    description: Name of chart, must match Chart.yaml
    required: true

  version:
    description: Chart semantic version
    required: true

  helm_path: 
    description: Folder where helm charts are stored
    required: true
    default: "helm"

  repository:
    description: Repository name for the chart 
    required: true
    default: 'lydteamet-helm-test'

  registry:
    description: Registry to push to
    required: true
    default: plattform.azurecr.io

  username:
    description: Username for registry
    required: true

  password:
    description: Password for registry
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set variables
      shell: bash
      run: export HELM_EXPERIMENTAL_OCI=1

    - name: Login to registry
      shell: bash
      run:  echo ${{ inputs.password }} | helm registry login -u ${{ inputs.username }} --password-stdin ${{ inputs.registry }}

    - name: Package chart
      shell: bash
      run: helm package ./${{ inputs.helm_path }}/${{ inputs.name }} --version ${{ inputs.version }}

    - name: Push chart
      shell: bash
      run: helm push ${{ inputs.name }}-${{ inputs.version }}.tgz oci://${{ inputs.registry }}/${{ inputs.repository }}
