---
name: Test action

on:
  push:
    branches: master

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: nrkno/lydteamet-helm-publish-action@master
        with:
          helm_path: ./helm/lydteamet-test-publish-action
          version: 0.0.$GITHUB_RUN_NUMBER
          registry: ${{ vars.PLATTFORM_CONTAINER_REGISTRY }}
          username: ${{ secrets.PLATTFORM_ACR_PUSH_CLIENT_ID }}
          password: ${{ secrets.PLATTFORM_ACR_PUSH_CLIENT_SECRET }}
