---
name: Test action

on:
  push:
    branches: master

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: ./.github/workflows/test.yaml
        with:
          helm_path: ./helm
          name: lydteamet-test-publish-action
          version: 0.0.1
          registry: ${{ secrets.PLATTFORM_CONTAINER_REGISTRY }}
          username: ${{ secrets.PLATTFORM_ACR_PUSH_CLIENT_ID }}
          password: ${{ secrets.PLATTFORM_ACR_PUSH_CLIENT_SECRET }}